### ISSUE TITLE
SignUp and Login

### ISSUE THREAD

**Issue by anjiniii** [8attery/SeeSaw-iOS#12]
### 상세 내용
로그인 화면 구현, Gif Image 추가

### Todo
- [x] 로그인 화면 구현
- [x] Gif Image 추가
- [x] 로그인 기능 연결
- [x] Keychain

### 라벨
- 예상 소요 시간: `E: 1h`
- 그룹: `iOS`
- 긴급도: `High`
