### ISSUE TITLE
ValueView

### ISSUE THREAD

**Issue by taewoojeong** [8attery/SeeSaw-iOS#13]
### 상세 내용
가치 설계 뷰 만들기

### Todo
- [x] 가치 설계 뷰 만들기
- [x] 가치 버튼 만들기
- [x] 연도버튼 누르면 연도별 가치 띄우기
- [x] 가치 버튼 누르면 나오는 프로젝트와 루틴 모달뷰 만들기
