### ISSUE TITLE
Energy Battery 화면 구현

### ISSUE THREAD

**Issue by anjiniii** [8attery/SeeSaw-iOS#30]
### 상세 내용
Energy Battery View 구현

### Todo
- [x] Battery Dashboard View 구현
- [x] 권한/목표 설정 페이지
- [x] 고속충전 설정
- [x] 배터리 내역 확인
- [x] 활동량 확인
- [x] 수면량 확인

### 라벨
- 예상 소요 시간: `E: 3h+`
- 그룹: `iOS`
- 긴급도: `High`
