### ISSUE TITLE
온보딩, 로그인 버그 수정

### ISSUE THREAD

**Issue by anjiniii** [8attery/SeeSaw-iOS#49]
### Todo
- [x] 가입약관
  - [x] 가입약관 선택 색상변경 어디에 어떠ㄴ 색으로 할까요?? 오래 안걸림!!
  - [x] 가입 약관 텍스트 추가
  - [x] 개인정보 어쩌구 삭제
- [x] 회원가입 완료
  - [x] 회원가입 완료 화면(세 번째 줄 -> 균형을 찾으러 가볼까요?)
- [x] 가치 설명
  - [x] 텍스트 위로
  - [x] Gif 이미지 추가
- [x] 가치 선택 / 저장
  - [x] 가치가 5글자 이상이면 2줄이 됨…(아나……)
  - [x] 가치를 여백 동일 왼쪽으로 정렬
  - [x] 가치 설정 화면에서 ‘에 가치를 두는 한 해를 보내고 싶어요’ 문구 삭제
  - [x] 추가 가치 마지막 새로운 줄에 추가
- [x] 카카오 로그인
  - [x] 카카오앱 로그인 후 idToken 서버 전달
