### ISSUE TITLE
마이 페이지 버그 수정

### ISSUE THREAD

**Issue by anjiniii** [8attery/SeeSaw-iOS#51]
### 상세 내용
My Page > 서버 연동, 버그 수정

### Todo
- [x] 닉네임 연동
- [x] 닉네임 변경
  - [x] 서버 연동
- [ ] 권한 설정
  - [ ] 건강 데이터 서버 연동
  - [x] 개인정보 정책?
- [x] 로그아웃
  - [x] keychain token 삭제
  - [x] 서버 연동
- [x] 회원탈퇴
  - [x] 텍스트 수정 반영
- [x] 빈 페이지 구현

### 라벨
- 예상 소요 시간: `E: 1h`
- 그룹: `iOS`
- 긴급도: `Mid`
