### ISSUE TITLE
온보딩 버그 수정

### ISSUE THREAD

**Issue by anjiniii** [8attery/SeeSaw-iOS#57]
### 상세 내용
온보딩 버그 수정

### Todo
- [x] 런치 스크린 이미지 변경
- [x] 이용약관 링크 연결
- [x] 로그인 이미지 수정
- [x] 온보딩 완료시 온보딩 생략
- [x] 탭바 메인화면에서만 보이도록 

### 라벨
- 예상 소요 시간: `E: 2h+`
- 그룹: `iOS`
- 긴급도: `Mid`
